'use client';
import { useEffect, useState } from 'react';
import { rowText as text, type AdminRow } from './admin-types';
type Activity={guests:AdminRow[];totals:Record<string,number>|null;daily:AdminRow[];recent:AdminRow[];error?:string};
export function ActivityPanel({guests,rsvps,checkins,marks,reservations,notify,reload}:{guests:AdminRow[];rsvps:AdminRow[];checkins:AdminRow[];marks:AdminRow[];reservations:AdminRow[];notify:(message:string)=>void;reload:()=>Promise<void>}) {
  const [data,setData]=useState<Activity|null>(null),[search,setSearch]=useState(''),[filter,setFilter]=useState('all'),[busy,setBusy]=useState(false);
  const load=async()=>{setBusy(true);try{await reload();const response=await fetch('/api/admin/activity',{cache:'no-store'});const result=await response.json() as Activity;if(!response.ok)throw new Error(result.error||'Aktivitas belum tersedia.');setData(result);}catch(e){notify(e instanceof Error?e.message:'Aktivitas belum tersedia.');}finally{setBusy(false);}};
  useEffect(()=>{let active=true;fetch('/api/admin/activity',{cache:'no-store'}).then(async r=>{const result=await r.json() as Activity;if(!r.ok)throw new Error(result.error);if(active)setData(result);}).catch(e=>{if(active)notify(e.message||'Aktivitas belum tersedia.');});return()=>{active=false;};},[]);
  const rows=(data?.guests??[]).filter(r=>(!search||`${text(r.display_name)} ${text(r.guest_group)}`.toLowerCase().includes(search.toLowerCase()))&&(filter==='all'||filter==='opened'&&Number(r.sessions)>0||filter==='unopened'&&!Number(r.sessions)||filter==='followup'&&Number(r.sessions)>0&&!r.attendance||filter==='arrived'&&!!r.checked_in_at));
  const at=(value:unknown)=>value?new Intl.DateTimeFormat('id-ID',{dateStyle:'medium',timeStyle:'short',timeZone:'Asia/Jakarta'}).format(new Date(text(value).replace(' ','T')+(text(value).includes('T')?'':'Z'))):'—';
  return <>
    <section className="admin-panel admin-wide cms-dashboard"><header className="cms-section-heading"><div><h2>Ringkasan undangan</h2><p>Dari link dibagikan sampai tamu tiba.</p></div><button type="button" disabled={busy} onClick={()=>void load()}>Refresh aktivitas</button></header>
      <dl className="cms-metrics">{[['Undangan aktif',guests.filter(g=>g.status==='active').length],['Link sudah dibuka',data?.totals?.opened??'—'],['RSVP masuk',rsvps.length],['Orang akan hadir',rsvps.reduce((n,r)=>n+(r.attendance==='yes'?Number(r.party_size)||0:0),0)],['Orang sudah tiba',checkins.reduce((n,r)=>n+(Number(r.party_size)||0),0)],['Mading perlu review',marks.filter(m=>m.moderation_status==='pending').length],['Hadiah dibooking',reservations.filter(r=>r.status==='reserved'||r.status==='purchased').length],['Sesi kunjungan',data?.totals?.sessions??'—']].map(([label,count])=><div key={String(label)}><dt>{label}</dt><dd>{count}</dd></div>)}</dl>
    </section>
    <section className="admin-panel admin-wide"><header className="cms-section-heading"><div><h2>Siapa yang membuka link</h2><p>Waktu ditampilkan dalam WIB. Nama adalah pemilik link; link yang diteruskan tetap tercatat atas nama pemiliknya.</p></div><a href="/api/admin/activity?export=csv" download>Export aktivitas CSV</a></header>
      <div className="guest-filters"><label>Cari tamu<input type="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Nama atau grup"/></label><label>Aktivitas<select value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">Semua tamu</option><option value="opened">Sudah buka</option><option value="unopened">Belum buka</option><option value="followup">Sudah buka, belum RSVP</option><option value="arrived">Sudah tiba</option></select></label></div>
      {!data?<p role="status">Memuat aktivitas…</p>:<div className="cms-scroll-table"><table><thead><tr><th>Tamu</th><th>Pertama buka</th><th>Terakhir buka</th><th>Sesi / halaman</th><th>RSVP</th><th>Kedatangan</th><th>Mading</th></tr></thead><tbody>{rows.map(r=><tr key={text(r.id)}><td><strong>{text(r.display_name)}</strong><small>{text(r.guest_group)}</small></td><td>{at(r.first_at)}</td><td>{at(r.last_at)}</td><td>{text(r.sessions)} / {text(r.views)}</td><td>{r.attendance==='yes'?'Hadir':r.attendance==='no'?'Tidak hadir':'Belum balas'}</td><td>{r.checked_in_at?`${r.arrived_people} orang · ${at(r.checked_in_at)}`:'Belum check-in'}</td><td>{text(r.marks)}</td></tr>)}</tbody></table>{!rows.length&&<p>Tidak ada tamu sesuai filter.</p>}</div>}
      <p className="cms-muted">Kunjungan dicatat setelah halaman terlihat di browser. Satu sesi berlangsung 30 menit. Browser yang memblokir pencatatan, Do Not Track, dan Global Privacy Control tidak dicatat. Kedatangan dihitung dari check-in, terpisah dari kunjungan website.</p>
    </section>
    <section className="admin-panel admin-wide"><h2>Aktivitas halaman terbaru</h2><div className="admin-table">{data?.recent.length?data.recent.map((r,i)=><article key={i}><strong>{text(r.display_name)||'Pengunjung umum'}</strong><span>{text(r.page)} · {text(r.views)} kali</span><small>{at(r.last_at)}</small></article>):<p>Belum ada kunjungan tercatat.</p>}</div></section>
  </>;
}
