'use client';
import { useEffect, useRef, useState } from 'react';
import type { ContentSection } from '@/lib/content-defaults';
import { WEBSITE_DEFAULTS, type WebsiteBlocks, type WebsiteConfig, type Localized } from '@/lib/website-content';

type SiteResponse={config:WebsiteConfig;blocks:WebsiteBlocks;media:Record<string,string>;error?:string};
type ContentResponse={sections:ContentSection[];values:Record<string,string>;error?:string};
export function ContentManager({notify,requestedMode='copy',onModeChange}:{notify:(message:string)=>void;requestedMode?:string;onModeChange?:(mode:string)=>void}) {
  const [data,setData]=useState<ContentResponse|null>(null),[config,setConfig]=useState<WebsiteConfig>(WEBSITE_DEFAULTS),[blocks,setBlocks]=useState<WebsiteBlocks|null>(null);
  const [loadError,setLoadError]=useState(''),[loadAttempt,setLoadAttempt]=useState(0);
  const [section,setSection]=useState('hero'),[query,setQuery]=useState(''),[page,setPage]=useState(0),[busy,setBusy]=useState(false);
  const [photoUrls,setPhotoUrls]=useState<Record<string,string>>({});
  const mode=requestedMode;
  const saved=useRef<{values:Record<string,string>;config:WebsiteConfig;blocks:WebsiteBlocks}|null>(null);
  useEffect(()=>{const protect=(event:BeforeUnloadEvent)=>{if(saved.current&&data&&blocks&&(JSON.stringify(data.values)!==JSON.stringify(saved.current.values)||JSON.stringify(config)!==JSON.stringify(saved.current.config)||JSON.stringify(blocks)!==JSON.stringify(saved.current.blocks))){event.preventDefault();event.returnValue='';}};window.addEventListener('beforeunload',protect);return()=>window.removeEventListener('beforeunload',protect);},[data,config,blocks]);
  useEffect(()=>{let alive=true;Promise.all([fetch('/api/admin/content',{cache:'no-store'}),fetch('/api/admin/website',{cache:'no-store'})]).then(async responses=>{const [copy,site]=await Promise.all([responses[0].json() as Promise<ContentResponse>,responses[1].json() as Promise<SiteResponse>]);if(responses.some(r=>!r.ok))throw new Error(copy.error||site.error);if(alive){saved.current={values:copy.values,config:site.config,blocks:site.blocks};setData(copy);setConfig(site.config);setBlocks(site.blocks);setPhotoUrls(site.media);}}).catch(e=>{if(alive){setLoadError('Konten tidak bisa dimuat. Coba lagi.');notify('Konten tidak bisa dimuat. Coba lagi.');}});return()=>{alive=false;};},[loadAttempt]);
  async function save(url:string,body:unknown){setBusy(true);try{const response=await fetch(url,{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify(body)});const result=await response.json() as {error?:string;url?:string};if(!response.ok)throw new Error(result.error||'Penyimpanan gagal.');if(url==='/api/admin/content'){const fresh=await fetch(url,{cache:'no-store'});const value=await fresh.json() as ContentResponse;if(!fresh.ok)throw new Error(value.error||'Konten gagal dimuat ulang.');const keys=Object.keys((body as {values:Record<string,string>}).values);setData(current=>current?{...current,values:{...current.values,...Object.fromEntries(keys.map(key=>[key,value.values[key]]))}}:value);if(saved.current)saved.current.values={...saved.current.values,...Object.fromEntries(keys.map(key=>[key,value.values[key]]))};}else if(saved.current){const value=body as {config?:WebsiteConfig;blocks?:WebsiteBlocks};if(value.config)saved.current.config=value.config;if(value.blocks)saved.current.blocks=value.blocks;}notify('Konten tersimpan. Buka ulang preview untuk melihat hasilnya.');}catch(e){notify(e instanceof Error?e.message:'Penyimpanan gagal.');}finally{setBusy(false);}}
  const update=(key:string,value:string)=>setData(current=>current?{...current,values:{...current.values,[key]:value}}:null);
  const selected=data?.sections.find(s=>s.id===section);
  const fields=selected?.fields.filter(f=>!query||`${f.label} ${data?.values[`${section}.${f.key}`]} ${data?.values[`id.${section}.${f.key}`]}`.toLowerCase().includes(query.toLowerCase()))??[];
  const visible=fields.slice(page*20,page*20+20);
  const saveFields=(keys:string[])=>void save('/api/admin/content',{values:Object.fromEntries(keys.flatMap(k=>[[k,data?.values[k]??''],[`id.${k}`,data?.values[`id.${k}`]??'']]))});
  const updateBlock=(kind:keyof WebsiteBlocks,index:number,field:string,value:unknown)=>setBlocks(current=>current?{...current,[kind]:current[kind].map((r,i)=>i===index?{...r,[field]:value}:r)}:null);
  const remove=(kind:keyof WebsiteBlocks,index:number)=>setBlocks(current=>current?{...current,[kind]:current[kind].filter((_,i)=>i!==index)}:null);
  const move=(kind:keyof WebsiteBlocks,index:number,offset:number)=>setBlocks(current=>{if(!current)return null;const rows=[...current[kind]];const target=index+offset;if(target<0||target>=rows.length)return current;[rows[index],rows[target]]=[rows[target],rows[index]];return {...current,[kind]:rows};});
  const add=(kind:keyof WebsiteBlocks)=>setBlocks(current=>{if(!current||current[kind].length>=24)return current;const id=`${kind}-${crypto.randomUUID().slice(0,8)}`;const item=kind==='photos'?{id,slot:`gallery-${crypto.randomUUID().slice(0,8)}`,caption:{en:'Caption to be added.',id:'Keterangan akan ditambahkan.'}}:{id,title:{en:'New title',id:'Judul baru'},body:{en:'',id:''},...(kind==='links'?{href:'/archive'}:{})};return {...current,[kind]:[...current[kind],item]};});
  function bilingual(value:Localized,onChange:(value:Localized)=>void,label:string,max=2000){return <div className="cms-bilingual"><label>{label} · Indonesia<textarea value={value.id} maxLength={max} rows={3} onChange={e=>onChange({...value,id:e.target.value})}/></label><label>{label} · English<textarea value={value.en} maxLength={max} rows={3} onChange={e=>onChange({...value,en:e.target.value})}/></label></div>;}
  return <section className="admin-panel admin-wide cms-content-manager"><header className="cms-section-heading"><div><h2>Seluruh konten website</h2><p>Teks dua bahasa, detail acara, susunan cerita, FAQ, foto, dan tautan.</p></div><a href="/" target="_blank" rel="noreferrer">Buka preview ↗</a></header>
    <div className="cms-subtabs">{[['copy','Teks & interface'],['event','Acara & SEO'],['story','Cerita'],['faq','FAQ'],['photos','Foto & caption'],['links','Tautan akhir']].map(([key,label])=><button type="button" key={key} className={mode===key?'on':''} onClick={()=>{onModeChange?.(key);}}>{label}</button>)}</div>
    {!data||!blocks?<div>{loadError?<><p role="alert">{loadError}</p><button type="button" onClick={()=>{setLoadError('');setLoadAttempt(n=>n+1);}}>Coba muat ulang</button></>:<p role="status">Memuat konten…</p>}</div>:<>
    {mode==='copy'&&<><div className="guest-filters"><label>Bagian<select value={section} onChange={e=>{setSection(e.target.value);setPage(0);setQuery('');}}>{data.sections.map(s=><option key={s.id} value={s.id}>{s.label} · {s.fields.length}</option>)}</select></label><label>Cari teks<input type="search" value={query} onChange={e=>{setQuery(e.target.value);setPage(0);}} placeholder="Cari kalimat, heading, atau label" /></label></div><p>Bahasa Indonesia dan Inggris disimpan terpisah. Kosongkan field untuk kembali ke teks bawaan. Cerita, FAQ, dan caption foto dikelola di tab masing-masing.</p>
      {visible.map(f=>{const key=`${section}.${f.key}`;return <article className="cms-copy-field" key={key}><h3>{f.label}</h3><div className="cms-bilingual"><label>Indonesia<textarea rows={3} value={data.values[`id.${key}`]??''} maxLength={section==="keepsake"?120:section==="keepsakeUi"?500:2000} onChange={e=>update(`id.${key}`,e.target.value)}/></label><label>English<textarea rows={3} value={data.values[key]??f.value} maxLength={section==="keepsake"?120:section==="keepsakeUi"?500:2000} onChange={e=>update(key,e.target.value)}/></label></div><button disabled={busy} type="button" onClick={()=>saveFields([key])}>Simpan teks ini</button></article>;})}
      <div className="cms-actions"><button type="button" disabled={busy||!visible.length} onClick={()=>saveFields(visible.map(f=>`${section}.${f.key}`))}>Simpan {visible.length} teks di halaman ini</button><button type="button" disabled={page===0} onClick={()=>setPage(p=>p-1)}>Sebelumnya</button><span>{page+1} / {Math.max(1,Math.ceil(fields.length/20))}</span><button type="button" disabled={(page+1)*20>=fields.length} onClick={()=>setPage(p=>p+1)}>Berikutnya</button></div>
    </>}
    {mode==='event'&&<form onSubmit={e=>{e.preventDefault();void save('/api/admin/website',{config});}}><div className="cms-bilingual">{Object.entries({firstName:'Nama pendek Bagas',secondName:'Nama pendek Iga',weddingDate:'Tanggal acara',akadTime:'Jam akad',receptionTime:'Jam resepsi',venueName:'Nama venue',venueCity:'Kota',venueAddress:'Alamat lengkap',mapsUrl:'Link Google Maps',metaTitle:'Judul website / SEO',metaDescription:'Deskripsi website / SEO',ogImage:'Gambar share / OG (URL)'}).map(([key,label])=><label key={key}>{label}<input type={key==='weddingDate'?'date':key.endsWith('Time')?'time':key==='mapsUrl'?'url':'text'} required maxLength={key==='metaTitle'?180:500} value={String(config[key as keyof WebsiteConfig])} onChange={e=>setConfig(c=>({...c,[key]:e.target.value}))}/></label>)}<label>Longitude<input type="number" step="any" min={-180} max={180} value={config.longitude} onChange={e=>setConfig(c=>({...c,longitude:Number(e.target.value)}))}/></label><label>Latitude<input type="number" step="any" min={-90} max={90} value={config.latitude} onChange={e=>setConfig(c=>({...c,latitude:Number(e.target.value)}))}/></label></div><label className="check"><input type="checkbox" checked={config.profilesEnabled} onChange={e=>setConfig(c=>({...c,profilesEnabled:e.target.checked}))}/>Tampilkan profil mempelai</label><label className="check"><input type="checkbox" checked={config.trackingEnabled} onChange={e=>setConfig(c=>({...c,trackingEnabled:e.target.checked}))}/>Catat aktivitas link undangan</label><button disabled={busy}>Simpan detail acara & SEO</button></form>}
    {(['story','faq','photos','links'] as const).filter(kind=>mode===kind).map(kind=><div key={kind}><p>Tambah, hapus, atau ubah urutan. Maksimal 24 item. Perubahan diterapkan setelah disimpan.</p>{blocks[kind].map((raw,index)=>{const r=raw as unknown as Record<string,unknown>;return <article className="cms-block" key={String(r.id)}><header className="cms-section-heading"><h3>{kind==='photos'?`Polaroid ${index+1}`:`Item ${index+1}`}</h3><div className="cms-actions"><button type="button" disabled={index===0} onClick={()=>move(kind,index,-1)}>Naik</button><button type="button" disabled={index===blocks[kind].length-1} onClick={()=>move(kind,index,1)}>Turun</button><button type="button" onClick={()=>remove(kind,index)}>Hapus</button></div></header>{kind==='photos'?<>{bilingual(r.caption as Localized,value=>updateBlock(kind,index,'caption',value),'Caption',500)}{photoUrls[String(r.slot)]&&<img className="cms-photo-preview" src={photoUrls[String(r.slot)]} alt="" />}<label>Foto (JPG, PNG, WebP, AVIF; maks. 5 MB)<input type="file" accept="image/jpeg,image/png,image/webp,image/avif" onChange={async e=>{const file=e.target.files?.[0];e.target.value='';if(!file)return;if(file.size>5*1024*1024){notify("Foto maksimal 5 MB.");return;}setBusy(true);try{const body=new FormData();body.set('file',file);const response=await fetch(`/api/admin/media/${r.slot}`,{method:'POST',body});const result=await response.json() as {error?:string;url?:string};if(!response.ok)throw new Error(result.error);if(result.url)setPhotoUrls(current=>({...current,[String(r.slot)]:result.url!}));notify('Foto terunggah. Simpan daftar untuk menerapkan urutan dan caption.');}catch(error){notify(error instanceof Error?error.message:'Upload gagal.');}finally{setBusy(false);}}}/></label><small>Slot {String(r.slot)} · JPG/PNG/WebP/AVIF, maks. 5 MB</small></>:<>{bilingual(r.title as Localized,value=>updateBlock(kind,index,'title',value),'Judul',200)}{bilingual(r.body as Localized,value=>updateBlock(kind,index,'body',value),'Isi')}{kind==='links'&&<label>Tujuan tautan<input value={String(r.href)} onChange={e=>updateBlock(kind,index,'href',e.target.value)} placeholder="/archive atau https://…"/></label>}</>}</article>;})}<div className="cms-actions"><button type="button" disabled={blocks[kind].length>=24||busy} onClick={()=>add(kind)}>Tambah {kind==='photos'?'polaroid':'item'}</button><button type="button" disabled={busy} onClick={()=>void save('/api/admin/website',{blocks})}>Simpan susunan & konten</button></div></div>)}
    </>}
  </section>;
}
