'use client';
/* eslint-disable @next/next/no-img-element */
import { useState } from 'react';
import { rowText as text,type AdminAction,type AdminRow } from './admin-types';
export function ModerationManager({marks,action}:{marks:AdminRow[];action:AdminAction}) {
  const [filter,setFilter]=useState('pending'),[query,setQuery]=useState(''),[busy,setBusy]=useState('');
  const rows=marks.filter(r=>(filter==='all'||r.moderation_status===filter)&&(!query||`${text(r.author_name)} ${text(r.guest_name)} ${text(r.message)}`.toLowerCase().includes(query.toLowerCase())));
  async function moderate(id:string,status:string){setBusy(id);try{await action('moderate_mark',{id,status});}finally{setBusy('');}}
  return <section className="admin-panel admin-wide"><header><h2>Mading & kartu pos</h2><p>{marks.filter(r=>r.moderation_status==='pending').length} menunggu review · {marks.filter(r=>r.moderation_status==='approved').length} disetujui</p></header><div className="guest-filters"><label>Status<select value={filter} onChange={e=>setFilter(e.target.value)}><option value="pending">Perlu approval</option><option value="approved">Disetujui</option><option value="rejected">Ditolak</option><option value="all">Semua kartu</option></select></label><label>Cari penulis atau pesan<input type="search" value={query} onChange={e=>setQuery(e.target.value)}/></label></div><p>Hanya kartu public yang sudah disetujui tampil di mading. Kartu private tetap untuk kalian berdua.</p><div className="cms-moderation-grid">{rows.map(r=><article className="cms-postcard" key={text(r.id)}><header><h3>{text(r.author_name)}</h3><p>Pemilik undangan: {text(r.guest_name)||text(r.author_name)}</p><small>{text(r.created_at)} · {text(r.visibility)} · {text(r.moderation_status)}</small></header>{!!r.drawing_key&&<a href={`/api/marks/${r.id}/image`} target="_blank" rel="noreferrer"><img src={`/api/marks/${r.id}/image`} alt={`Gambar dari ${text(r.author_name)}`} loading="lazy"/></a>}<p className="cms-postcard-message" style={{whiteSpace:"pre-wrap"}}>{text(r.message)||'Kartu gambar tanpa pesan.'}</p><div className="cms-actions">{[['approved','Approve'],['rejected','Tolak'],['pending','Kembali ke review']].filter(([status])=>status!==r.moderation_status).map(([status,label])=><button key={status} type="button" disabled={!!busy} onClick={()=>void moderate(text(r.id),status)}>{label}</button>)}</div></article>)}</div>{!rows.length&&<p>Tidak ada kartu sesuai filter.</p>}</section>;
}
