// Live public copy fields. Event settings and repeatable collections have their own editors.
export const ACTIVE_CONTENT_KEYS = [
  "archive.desc",
  "archive.head",
  "beyond.arch t",
  "beyond.head",
  "details.akad",
  "details.arah",
  "details.head",
  "details.kicker",
  "details.resepsi",
  "details.sub",
  "footer.amplop",
  "footer.edisi",
  "gift.cta",
  "gift.desc",
  "gift.head",
  "gift.sub",
  "hero.env greet",
  "hero.env skip",
  "hero.hero date",
  "hero.hero head",
  "hero.hero sub",
  "keepsake.back",
  "keepsake.editionLabel",
  "keepsake.forLabel",
  "keepsake.front",
  "keepsake.genericRecipient",
  "keepsake.hint",
  "keepsake.love",
  "keepsake.signatureNames",
  "keepsake.note1",
  "keepsake.note2",
  "keepsake.return",
  "keepsake.turn",
  "mark.desc",
  "mark.head",
  "mark.sub",
  "misc.di",
  "misc.seal",
  "peta.err",
  "peta.gmaps",
  "peta.load",
  "peta.still",
  "profil.b_cap",
  "profil.b_family",
  "profil.b_found",
  "profil.b_known",
  "profil.head",
  "profil.i_cap",
  "profil.i_family",
  "profil.i_found",
  "profil.i_known",
  "profil.i_nama",
  "profil.kicker",
  "profil.nama1",
  "profil.quote label",
  "profil.quote label2",
  "profil.quote1",
  "profil.quote2",
  "rsvp.hadir",
  "rsvp.head",
  "story.head",
  "useful.head",
  "useful.sub"
] as const;
