// Authored public UI strings, managed independently in English and Indonesian.
export function copyKey(text:string) { let hash=2166136261; for(const character of text.trim()) { hash^=character.charCodeAt(0); hash=Math.imul(hash,16777619); } return 'copy.'+(hash>>>0).toString(16); }
export const PUBLIC_COPY = [
  "1 November 2026",
  "1 November 2026 · Pandiga, Cimahi",
  "18:00 WIB",
  "A B embracing a bending I.",
  "A card to keep.",
  "A contact person will be added closer to the date.",
  "A day for us. A place for you.",
  "A favourite place or everyday ritual.",
  "A few frames from our life together.",
  "A few things",
  "A few things from our collection.",
  "A few things that stayed.",
  "A few things we’re saving room for",
  "A few words about this next chapter will live here.",
  "A garden on the front. A note for you on the back.",
  "A little context",
  "A little note, if you like.",
  "A little of our story",
  "A little of the day,",
  "A little room for something thoughtful.",
  "A little space, for now.",
  "A little word",
  "A note for us",
  "A place for something small.",
  "A place, a habit, a little thing she loves.",
  "A postcard from you",
  "A reply from",
  "A short note about how we first met will live here.",
  "A small detail about Bagas, from Iga.",
  "A small detail about Iga, from Bagas.",
  "A small moment from our time together will be added here.",
  "A small place for an ordinary thing that means something to us. The story is coming.",
  "Aa",
  "Accepted / 01.11.26",
  "According to Bagas",
  "According to Iga",
  "Add Akad to calendar",
  "Add Reception to calendar",
  "Add to calendar",
  "Add words",
  "Address and entrance",
  "Akad",
  "Akad 14:00 ·",
  "Along the way",
  "Already booked",
  "An original photograph from Bagas and Iga will live here. No substitute memory has been invented.",
  "And just like that,",
  "Apparently venues care about these things.",
  "Apple / Outlook (.ics)",
  "Approved",
  "Approved guest postcards will appear here.",
  "Approved postcards from every guest.",
  "Approved postcards only. No likes, replies, rankings, or counters.",
  "Archive",
  "Archive / Mark / 01",
  "As observed by Bagas",
  "As observed by Iga",
  "Audio unavailable.",
  "B",
  "B embracing the bending I.",
  "B × I",
  "Back to Archive",
  "Bagas",
  "Bagas × Iga",
  "Bagas × Iga · 01.11.2026",
  "Bagas, as himself.",
  "Beyond the invitation",
  "Book this gift",
  "Booked by",
  "Booked under",
  "Booking cancelled. The gift is available again.",
  "Both sides, kept together. Open the file in a browser, even offline.",
  "Browse the collection",
  "Browse the collections",
  "Cancel booking",
  "Cancelling makes this gift available to another guest.",
  "Card font",
  "Card font — click to try",
  "Card stack",
  "Card style",
  "Card style — click to try",
  "Card updated.",
  "Cash gift",
  "Children and plus-ones",
  "Choose a gift to book. Other invited guests will see your name beside it.",
  "Choose a piece. Stay a little.",
  "Choose a story to read.",
  "Cimahi",
  "Classic",
  "Clean",
  "Clear",
  "Click the paper and write — or switch to Draw and sketch over it.",
  "Close",
  "Close booking",
  "Close guest pass",
  "Close keepsake preview",
  "Confirm booking",
  "Confirm cancellation",
  "Confirm purchase",
  "Contact person",
  "Continue",
  "Copied.",
  "Copy details",
  "Copy pass code",
  "Copy unavailable. Select the code above to copy it.",
  "Copy unavailable. Select the details above to copy them.",
  "Curated objects will be added here.",
  "Details",
  "Details to follow",
  "Dietary notes",
  "Download calendar file for",
  "Download card",
  "Draw",
  "Drawing tools",
  "Drawn, not written.",
  "Dress code",
  "Edit",
  "Entry ready for original material.",
  "Eraser",
  "Everyone",
  "Explore this collection",
  "Family",
  "Family details will be added.",
  "Filter archive",
  "For",
  "For Bagas",
  "For Iga",
  "For Our Home",
  "For our very special guest",
  "For those who know one of us better.",
  "From",
  "From the archive",
  "Gift booked for you.",
  "Gift catalogue",
  "Gift catalogue is unavailable.",
  "Gift collections",
  "Gift could not be updated.",
  "Gift could not be updated. Please try again.",
  "Gifts",
  "Gifts are temporarily unavailable. Please try again.",
  "Google Calendar",
  "Guest",
  "Guest check-in QR code",
  "Guest edition",
  "Guest mark /",
  "Guest marks",
  "Guest names",
  "Guest pass is temporarily unavailable. Please try again.",
  "Guest postcard installation preview",
  "Guest-specific guidance will remain attached to each private invitation.",
  "Handwriting",
  "Held for you",
  "Here’s when and where to find us. We can’t wait to see you there.",
  "How we got here.",
  "I",
  "I can’t make it.",
  "Iga",
  "Iga, as herself.",
  "Image unavailable.",
  "In review",
  "Info",
  "Ink colour",
  "Interactive map around Pandiga Cimahi. Use drag, the controls, or arrow keys to explore.",
  "Invitation",
  "Invitation for",
  "I’ll be there.",
  "I’ll miss this one.",
  "I’ve bought it",
  "Jawa Barat 40513",
  "Jl. Sirnarasa No.11, Cibabat",
  "Jl. Sirnarasa No.11, Cibabat,",
  "Just Bagas & Iga",
  "Kec. Cimahi Utara, Kota Cimahi,",
  "Keep a little of the day",
  "Keep this mark",
  "Keeping your mark…",
  "Kept for Bagas × Iga",
  "Kept.",
  "Known for",
  "Leave a",
  "Leave a Mark",
  "Leave a mark",
  "Listen when you like.",
  "Live map unavailable right now.",
  "Loading more postcards…",
  "Loading the actual roads around Pandiga…",
  "Loading the wall…",
  "Loading your answer…",
  "Loading your postcards…",
  "Made with unreasonable attention to detail",
  "Make a mess.",
  "Map controls",
  "Map shown in a still state.",
  "Maps",
  "Mark",
  "Marked as purchased.",
  "Marks",
  "Name on your keepsake",
  "New card",
  "Next card",
  "Next photograph",
  "Next piece",
  "No items have been added to this category yet.",
  "Nothing here yet — approved postcards will fill the wall.",
  "Nothing here yet — your card will appear beside this note once you keep it.",
  "Nothing in this collection yet.",
  "Number of guests",
  "OPEN IN GOOGLE MAPS",
  "Object",
  "Object photograph",
  "Observation from Bagas will be added.",
  "Observation from Iga will be added.",
  "On the wall",
  "One of our earliest conversations started with Iga’s name. Bagas asked why her parents chose it, then joked that perhaps she was his missing",
  "One of our first conversations was about Iga’s name. Bagas wondered why her parents chose it, then joked that perhaps she was his missing rib.",
  "Only used for this keepsake.",
  "Only what we really kept.",
  "Open Google Calendar for",
  "Open directions",
  "Open directions to Pandiga Cimahi in Google Maps",
  "Open one. Take your time.",
  "Open photograph",
  "Open postcard from",
  "Open purchase link",
  "Open the archive",
  "Open the gift catalogue",
  "Open the invitation",
  "Open this from your personal invitation.",
  "Open this story",
  "Open your keepsake",
  "Open your postcard",
  "Opening the collection…",
  "Original material",
  "Original sketches and iterations can be added here later.",
  "Our favourite people. One very good reason to gather.",
  "Our names, the date, and a place to meet.",
  "PNG · 900 × 1200",
  "Pandiga",
  "Pandiga Cimahi",
  "Pandiga, Cimahi",
  "Parking and accessibility",
  "Parking, entrance, and accessibility guidance will be added after venue confirmation.",
  "Pen",
  "People",
  "Photograph",
  "Photograph 01 — caption to be added.",
  "Photograph 02 — caption to be added.",
  "Photograph 03 — caption to be added.",
  "Photograph 04 — caption to be added.",
  "Photograph 05 — caption to be added.",
  "Photograph 06 — caption to be added.",
  "Photograph to come.",
  "Photograph viewer",
  "Photographs",
  "Photographs, objects, and little things that became our things.",
  "Photographs, objects, and other evidence. Only the real material makes it into the collection.",
  "Portrait of Bagas",
  "Portrait of Iga",
  "Postcard",
  "Postcard drawing area",
  "Postcards",
  "Postcards are closed for now. The wall remains open.",
  "Postcards from our guests",
  "Practical wedding links",
  "Prefer something simpler?",
  "Preparing image…",
  "Preparing your card…",
  "Preparing your digital keepsake…",
  "Preparing your guest pass…",
  "Preparing your reply paper…",
  "Preview my answer",
  "Preview my reply",
  "Preview only — no answer or postcard was saved.",
  "Preview only — nothing was saved.",
  "Preview only — open your personal invitation to save this.",
  "Preview only — open your personal invitation to save your reply.",
  "Previous card",
  "Previous photograph",
  "Previous piece",
  "Private delivery information",
  "Process material",
  "Purchased",
  "Purchased by",
  "Purchased by you",
  "Put it back",
  "RSVP",
  "RSVP is closed. Thank you for being part of our day.",
  "Read more",
  "Reception",
  "Redo",
  "Refresh the collection",
  "Release",
  "Reload the invitation",
  "Reply received",
  "Reservation released.",
  "Reserve quietly",
  "Reserved",
  "Reserved for something real.",
  "Reserved for you.",
  "Reset map",
  "Return to invitation",
  "Return to the collection",
  "Return to the front",
  "Same place,",
  "Save back as image",
  "Save digital keepsake",
  "Save front as image",
  "Save guest pass",
  "Save my answer",
  "Save my reply",
  "Saving your answer…",
  "Saving your choice…",
  "Saving…",
  "Scroll sideways to explore all three collections.",
  "Scroll to explore. Tap a card to read.",
  "Scrollable postcard wall",
  "See every postcard",
  "See guest marks",
  "See you in Cimahi.",
  "Selected moments.",
  "Send my postcard",
  "Show this QR at the entrance. Save the image before you leave.",
  "Skip opening",
  "Skip to the invitation",
  "Some things were",
  "Something from you",
  "Something that survived.",
  "Start-time reminder. End time to be confirmed.",
  "Still choosing.",
  "Sunday",
  "Swipe to read another postcard.",
  "Take a closer look",
  "Tell us if you’re coming. Leave a little love, if you like.",
  "Text / drawing",
  "Thank you for being part of our day.",
  "That is all the symbol needs to say. The rest belongs to us.",
  "The",
  "The Archive",
  "The B, the bending I, and the joke that stayed.",
  "The Gallery",
  "The Mark",
  "The Marks",
  "The beginning",
  "The card could not be prepared. Please try again.",
  "The catalogue opens from a private invitation so reservations stay private.",
  "The catalogue opens from your private invitation. Each booking is saved under your name.",
  "The catalogue uses your private invitation token so a reservation can belong to the correct guest.",
  "The collection",
  "The day ahead",
  "The day we’ve been dreaming of",
  "The day we’ve been dreaming of is",
  "The details",
  "The digital file could not be prepared.",
  "The dress code will be added after it is confirmed.",
  "The gift catalogue will open later.",
  "The identity began with an old joke about a missing rib. The B holds the curved I without turning the story into a slogan.",
  "The image could not be prepared.",
  "The invitation ends here.",
  "The louder part.",
  "The mark",
  "The official part.",
  "The postcard studio is closed for now. The wall remains open.",
  "The questions someone was going to ask anyway.",
  "The real story is still to come.",
  "The reply paper could not be loaded.",
  "The rest stays open.",
  "The special day of",
  "The two of us,",
  "The useful bits",
  "The wall",
  "The wall could not be loaded. Try again.",
  "The wall is quiet for now.",
  "Then and now. Coming later.",
  "Things our guests left behind",
  "Things we kept.",
  "Things worth keeping",
  "Things you left.",
  "This gift changed while you were viewing it. Its availability has been refreshed.",
  "This gift changed while you were viewing it. Please refresh and try again.",
  "This is a quiet reservation list, not a shop. Your name stays private when you reserve.",
  "This place is held for a real object, receipt, note, or other ordinary evidence worth keeping.",
  "This records your purchase and keeps the gift unavailable to other guests.",
  "To be added.",
  "Together, with you.",
  "Too many gift updates. Please try again shortly.",
  "Try again",
  "Try loading my answer again",
  "Turn it over",
  "Typewriter",
  "Undo",
  "Up to",
  "Update this card",
  "Use the controls, drag, or arrow keys to explore the actual roads around the venue. The directions link below opens Google Maps.",
  "Use this name",
  "Useful bits",
  "Usually found",
  "View the envelope again",
  "Visible because",
  "WE'LL MISS YOU. THANKS FOR LETTING US KNOW.",
  "WIB",
  "We could not confirm this gift update. Please contact us before retrying.",
  "Wedding details",
  "Wedding schedule",
  "We’ll keep it.",
  "We’re choosing a photograph for this spot. Some things deserve a little time.",
  "We’re doing",
  "We’re getting married.",
  "We’re saving room for.",
  "Who may see it after review?",
  "Will you be there?",
  "With love,",
  "Write",
  "Write it. Draw it. Make it yours. Nothing appears publicly before we review it.",
  "Write something you want us to keep.",
  "Write something, draw something, or do both.",
  "Write, draw, or leave this blank. Either answer is welcome.",
  "YOU'RE ON THE LIST.",
  "Years later, the joke became the starting point for this mark. Drawing an actual rib felt too literal, so the idea was reduced: a B holding a bending I.",
  "You are editing a card you kept before. Saving sends it back for review.",
  "Your answer",
  "Your answer could not be loaded. Try again.",
  "Your answer could not be saved.",
  "Your answer is already saved.",
  "Your answer is saved. See you there.",
  "Your answer is saved. Thank you for letting us know.",
  "Your attendance stays private. A postcard is optional.",
  "Your changed answer has not been saved yet.",
  "Your digital keepsake.",
  "Your guest pass",
  "Your mark could not be saved.",
  "Your message",
  "Your name",
  "Your name will be visible to other invited guests beside this gift.",
  "Your postcards",
  "Your reply",
  "You’re on the list",
  "Zoom in",
  "Zoom out",
  "a headcount.",
  "a very special day.",
  "all",
  "and approximately 1 billion tokens.",
  "another guest",
  "as observed by the other.",
  "audio",
  "available",
  "conversation",
  "entries",
  "entry",
  "from you.",
  "guest",
  "guests",
  "holds this reservation.",
  "home",
  "item",
  "items",
  "just for you.",
  "mark",
  "note",
  "object",
  "optional",
  "other",
  "our favourite people",
  "photo",
  "photograph",
  "place",
  "purchased",
  "reserved",
  "to be added",
  "will live here.",
  "worth keeping.",
  "you",
  "“A few words from Bagas will live here.”",
  "“A few words from Iga will live here.”",
  "“A real sentence will live here.”"
] as const;
