// Authored interface copy only. Guest names, messages and personal archive entries
// stay in their original language; no machine translation or external service.
export const indonesian: Record<string, string> = {
  "We’re choosing a photograph for this spot. Some things deserve a little time.": "Kami sedang memilih foto untuk ruang ini. Ada kenangan yang tak perlu diburu-buru.",
  "A small place for an ordinary thing that means something to us. The story is coming.": "Ruang kecil untuk benda biasa yang berarti bagi kami. Ceritanya segera menyusul.",
  "Photographs, objects, and little things that became our things.": "Foto, benda, dan hal-hal kecil yang akhirnya jadi cerita kami.",
  "One of our first conversations was about Iga’s name. Bagas wondered why her parents chose it, then joked that perhaps she was his missing rib.": "Salah satu percakapan pertama kami bermula dari nama Iga. Bagas penasaran mengapa orang tuanya memilih nama itu, lalu bercanda: mungkin Iga adalah tulang rusuknya yang hilang.",
  "A day for us. A place for you.": "Hari kami. Tempat untukmu.",
  "Together, with you.": "Bersama, denganmu.",
  "We’re getting married.": "Kami akan menikah.",
  "Our favourite people. One very good reason to gather.": "Orang-orang tersayang. Satu alasan indah untuk berkumpul.",
  "The day we’ve been dreaming of": "Hari yang kami nantikan",
  "The special day of": "Hari bahagia",
  "Sunday": "Minggu",
  "Reception": "Resepsi",
  "Wedding details": "Detail acara",
  "Continue": "Selanjutnya",
  "You’re on the list": "Kami tunggu kehadiranmu",
  "Close": "Tutup",
  "Info": "Info",
  "Maps": "Peta",
  "Useful bits": "Info lainnya",
  "For our very special guest": "Teruntuk tamu spesial kami",
  "Skip opening": "Langsung masuk",
  "Skip to the invitation": "Langsung ke undangan",
  "Open the invitation": "Buka undangan",
  "The details": "Detail acara",
  "Same place,": "Satu tempat,",
  "a very special day.": "hari yang istimewa.",
  "Here’s when and where to find us. We can’t wait to see you there.": "Ini waktu dan tempatnya. Tinggal kamu yang kami tunggu.",
  "The official part.": "Saat janji diucapkan.",
  "The louder part.": "Saat bahagia dirayakan.",
  "Open directions": "Petunjuk arah",
  "Loading the actual roads around Pandiga…": "Menyiapkan peta menuju Pandiga…",
  "Live map unavailable right now.": "Peta belum dapat ditampilkan.",
  "OPEN IN GOOGLE MAPS": "BUKA GOOGLE MAPS",
  "Use the controls, drag, or arrow keys to explore the actual roads around the venue. The directions link below opens Google Maps.": "Geser peta, gunakan tombol kontrol atau tombol panah. Petunjuk arah tersedia di Google Maps.",
  "Map shown in a still state.": "Peta ditampilkan tanpa animasi.",
  "Interactive map around Pandiga Cimahi. Use drag, the controls, or arrow keys to explore.": "Peta interaktif Pandiga Cimahi. Geser atau gunakan kontrol dan tombol panah.",
  "Map controls": "Kontrol peta",
  "Zoom in": "Perbesar",
  "Zoom out": "Perkecil",
  "Reset map": "Atur ulang peta",
  "For those who know one of us better.": "Kalau selama ini baru kenal salah satu dari kami.",
  "The two of us,": "Kami berdua,",
  "as observed by the other.": "di mata satu sama lain.",
  "Portrait of Bagas": "Potret Bagas",
  "Portrait of Iga": "Potret Iga",
  "to be added": "akan hadir di sini",
  "Bagas, as himself.": "Bagas, apa adanya.",
  "Iga, as herself.": "Iga, apa adanya.",
  "Known for": "Paling dikenal karena",
  "Usually found": "Biasanya ditemukan",
  "According to Iga": "Kata Iga",
  "According to Bagas": "Kata Bagas",
  "Observation from Iga will be added.": "Menunggu cerita langsung dari Iga.",
  "Observation from Bagas will be added.": "Menunggu cerita langsung dari Bagas.",
  "“A real sentence will live here.”": "“Cerita aslinya menyusul di sini.”",
  "From the archive": "Dari arsip kami",
  "Some things were": "Ada yang sederhana,",
  "worth keeping.": "tapi layak disimpan.",
  "Photographs, objects, and other evidence. Only the real material makes it into the collection.": "Foto, benda, dan hal-hal kecil yang tinggal. Semua punya cerita, semuanya nyata.",
  "The mark": "Simbol kami",
  "The Mark": "Simbol Kami",
  "A B embracing a bending I.": "B yang memeluk I yang melengkung.",
  "The identity began with an old joke about a missing rib. The B holds the curved I without turning the story into a slogan.": "Berawal dari candaan tentang tulang rusuk yang hilang. Kini, B memeluk I yang melengkung. Ceritanya sederhana; artinya milik kami.",
  "Photograph": "Foto",
  "Reserved for something real.": "Tempat untuk kenangan asli.",
  "An original photograph from Bagas and Iga will live here. No substitute memory has been invented.": "Foto asli kami akan hadir di sini. Kenangan memang tak perlu pengganti.",
  "Object": "Benda",
  "Something that survived.": "Yang masih kami simpan.",
  "This place is held for a real object, receipt, note, or other ordinary evidence worth keeping.": "Untuk benda, nota, catatan, atau hal biasa yang ternyata berarti.",
  "Turn it over": "Balik kartunya",
  "Return to the front": "Kembali ke depan",
  "Open the archive": "Buka arsip",
  "Will you be there?": "Bisa datang?",
  "We’re doing": "Kami sedang",
  "a headcount.": "menghitung kursi.",
  "Apparently venues care about these things.": "Ternyata, pihak venue juga ingin tahu.",
  "Invitation for": "Undangan untuk",
  "our favourite people": "orang-orang tersayang",
  "Your answer": "Jawabanmu",
  "I’ll be there.": "Aku akan hadir.",
  "I’ll miss this one.": "Belum bisa hadir.",
  "Number of guests": "Jumlah tamu",
  "Guest names": "Nama tamu",
  "Dietary notes": "Catatan kebutuhan makanan",
  "A note for us": "Pesan untuk kami",
  "optional": "opsional",
  "Saving…": "Menyimpan…",
  "Save my answer": "Simpan jawaban",
  "Preview my answer": "Pratinjau jawaban",
  "Saving your answer…": "Menyimpan jawabanmu…",
  "Preview only — open your personal invitation to save this.": "Ini pratinjau. Buka tautan undangan pribadimu untuk menyimpan jawaban.",
  "Preview only — nothing was saved.": "Ini pratinjau. Jawaban belum disimpan.",
  "Your answer could not be saved.": "Jawaban belum tersimpan. Silakan coba lagi.",
  "YOU'RE ON THE LIST.": "KAMI TUNGGU KEHADIRANMU.",
  "WE'LL MISS YOU. THANKS FOR LETTING US KNOW.": "KAMI AKAN MERINDUKANMU. TERIMA KASIH SUDAH MEMBERI KABAR.",
  "Accepted / 01.11.26": "Tercatat / 01.11.26",
  "The useful bits": "Yang perlu kamu tahu",
  "The questions someone was going to ask anyway.": "Sebelum kamu sempat bertanya.",
  "Dress code": "Pakaian",
  "Details to follow": "Segera dikabarkan",
  "The dress code will be added after it is confirmed.": "Panduan pakaian akan kami kabarkan setelah dikonfirmasi.",
  "Address and entrance": "Alamat dan pintu masuk",
  "Parking and accessibility": "Parkir dan aksesibilitas",
  "Parking, entrance, and accessibility guidance will be added after venue confirmation.": "Panduan parkir, pintu masuk, dan aksesibilitas akan kami lengkapi bersama pihak venue.",
  "Children and plus-ones": "Anak-anak dan pendamping",
  "Guest-specific guidance will remain attached to each private invitation.": "Informasi jumlah tamu dan pendamping tersedia di undangan pribadimu.",
  "Contact person": "Narahubung",
  "A contact person will be added closer to the date.": "Narahubung akan kami tambahkan menjelang hari acara.",
  "A few things": "Beberapa hal",
  "We’re saving room for.": "Untuk rumah dan hari-hari kami.",
  "The catalogue opens from a private invitation so reservations stay private.": "Katalog dibuka melalui undangan pribadi, agar pilihan hadiahmu tetap privat.",
  "For Bagas": "Untuk Bagas",
  "For Iga": "Untuk Iga",
  "For Our Home": "Untuk Rumah Kami",
  "Curated objects will be added here.": "Pilihan kami akan hadir di sini.",
  "Open the gift catalogue": "Buka katalog hadiah",
  "Leave a mark": "Tinggalkan jejak",
  "Make a mess.": "Tulis. Coret. Gambar.",
  "We’ll keep it.": "Akan kami simpan.",
  "Write something, draw something, or do both.": "Satu pesan, satu gambar, atau keduanya.",
  "Open your postcard": "Buka kartu posmu",
  "See guest marks": "Lihat jejak para tamu",
  "Text / drawing": "Tulisan / gambar",
  "Something from you": "Sesuatu darimu",
  "will live here.": "akan tinggal di sini.",
  "Kept for Bagas × Iga": "Disimpan untuk Bagas × Iga",
  "Beyond the invitation": "Di balik undangan",
  "The invitation ends here.": "Undangan sampai di sini.",
  "The rest stays open.": "Cerita terus berlanjut.",
  "The Archive": "Arsip Kami",
  "Things we kept.": "Yang kami simpan.",
  "The Marks": "Jejak Tamu",
  "Things you left.": "Yang kamu tinggalkan.",
  "The Gallery": "Galeri",
  "Then and now. Coming later.": "Dulu dan kini. Segera hadir.",
  "Guest edition": "Edisi tamu",
  "Made with unreasonable attention to detail": "Dibuat dengan perhatian yang agak berlebihan",
  "and approximately 1 billion tokens.": "dan kurang lebih 1 miliar token.",
  "View the envelope again": "Lihat amplopnya lagi",
  "Invitation": "Undangan",
  "Guest marks": "Jejak tamu",
  "Archive": "Arsip",
  "Return to invitation": "Kembali ke undangan",
  "Things worth keeping": "Yang layak disimpan",
  "The": "Ruang",
  "A few things that stayed.": "Beberapa hal yang tinggal.",
  "Open one. Take your time.": "Buka satu. Tak perlu buru-buru.",
  "The collection": "Koleksi kami",
  "entry": "cerita",
  "entries": "cerita",
  "all": "semua",
  "mark": "simbol",
  "photo": "foto",
  "object": "benda",
  "note": "catatan",
  "place": "tempat",
  "Original material": "Materi asli",
  "Entry ready for original material.": "Ruang untuk cerita aslinya.",
  "Open this story": "Buka cerita ini",
  "The B, the bending I, and the joke that stayed.": "B, I yang melengkung, dan candaan yang menetap.",
  "Archive / Mark / 01": "Arsip / Simbol / 01",
  "B embracing the bending I.": "B memeluk I yang melengkung.",
  "One of our earliest conversations started with Iga’s name. Bagas asked why her parents chose it, then joked that perhaps she was his missing": "Salah satu percakapan pertama kami dimulai dari nama Iga. Bagas bertanya mengapa orang tuanya memilih nama itu, lalu bercanda: mungkin Iga adalah",
  "Years later, the joke became the starting point for this mark. Drawing an actual rib felt too literal, so the idea was reduced: a B holding a bending I.": "Bertahun-tahun kemudian, candaan itu menjadi awal dari simbol ini. Bukan gambar tulang rusuk, melainkan B yang memeluk I yang melengkung.",
  "That is all the symbol needs to say. The rest belongs to us.": "Cukup itu yang simbol ini ceritakan. Selebihnya milik kami.",
  "Process material": "Prosesnya",
  "Original sketches and iterations can be added here later.": "Sketsa asli dan perkembangannya akan menyusul di sini.",
  "Back to Archive": "Kembali ke arsip",
  "Things our guests left behind": "Yang ditinggalkan orang-orang tersayang",
  "Guest": "Jejak",
  "Marks": "Tamu",
  "Approved postcards only. No likes, replies, rankings, or counters.": "Kartu pos yang sudah ditinjau. Tanpa suka, balasan, atau peringkat. Cukup kenangan.",
  "The wall is quiet for now.": "Dinding ini masih menunggu cerita.",
  "Approved guest postcards will appear here.": "Kartu pos tamu akan tampil setelah kami tinjau.",
  "Guest mark /": "Jejak tamu /",
  "Gift catalogue": "Katalog hadiah",
  "Open this from your personal invitation.": "Buka dari undangan pribadimu, ya.",
  "The catalogue uses your private invitation token so a reservation can belong to the correct guest.": "Tautan undangan pribadimu membantu kami mencatat pilihan hadiah dengan tepat dan tetap privat.",
  "Pen": "Pena", "Eraser": "Penghapus", "Undo": "Urungkan", "Redo": "Ulangi", "Clear": "Bersihkan",
  "From": "Dari", "Add words": "Tambahkan kata-kata",
  "Write something you want us to keep.": "Tulis sesuatu yang ingin kamu titipkan pada kami.",
  "Who may see it after review?": "Siapa yang boleh melihat setelah ditinjau?",
  "Everyone": "Semua orang", "Just Bagas & Iga": "Hanya Bagas & Iga",
  "Keep this mark": "Simpan jejak ini", "Keeping your mark…": "Menyimpan jejakmu…", "Kept.": "Tersimpan.",
  "Your mark could not be saved.": "Jejakmu belum tersimpan. Silakan coba lagi.",
  "Leave a Mark": "Tinggalkan Jejak", "Leave a": "Tinggalkan", "Mark": "Jejak",
  "A postcard from you": "Sebuah kartu pos darimu",
  "Write it. Draw it. Make it yours. Nothing appears publicly before we review it.": "Tulis, gambar, sesukamu. Tidak ada yang tampil untuk publik sebelum kami tinjau.",
  "For": "Untuk",
  "A few things we’re saving room for": "Beberapa hal untuk hari-hari kami",
  "Gifts": "Hadiah",
  "This is a quiet reservation list, not a shop. Your name stays private when you reserve.": "Daftar kecil untuk memudahkanmu memilih hadiah. Nama dan pilihanmu tetap privat.",
  "Private delivery information": "Informasi pengiriman privat",
  "Visible because": "Terlihat karena",
  "holds this reservation.": "memegang reservasi ini.",
  "No items have been added to this category yet.": "Pilihan untuk kategori ini akan segera hadir.",
  "Object photograph": "Foto benda",
  "Reserve quietly": "Pilih hadiah ini", "Release": "Batalkan pilihan", "I’ve bought it": "Sudah kubeli",
  "Open purchase link": "Lihat tempat membeli", "Purchased": "Sudah dibeli", "Reserved": "Sudah dipilih",
  "Prefer something simpler?": "Ingin yang lebih sederhana?", "Cash gift": "Tanda kasih", "Copy details": "Salin detail",
  "Gift catalogue is unavailable.": "Katalog belum bisa dibuka. Silakan coba lagi.",
  "Gift could not be updated.": "Pilihan hadiah belum tersimpan. Silakan coba lagi.",
  "Reserved for you.": "Tercatat sebagai pilihanmu.", "Reservation released.": "Pilihanmu sudah dibatalkan.", "Marked as purchased.": "Tercatat sudah dibeli.", "Copied.": "Tersalin.",
  "available": "tersedia", "reserved": "sudah dipilih", "purchased": "sudah dibeli", "home": "rumah",
  "Drawing tools": "Alat menggambar", "Ink colour": "Warna tinta", "Postcard drawing area": "Area menggambar kartu pos",
  "Wedding schedule": "Jadwal acara", "Gift collections": "Koleksi hadiah",
  "Practical wedding links": "Tautan informasi acara", "Open directions to Pandiga Cimahi in Google Maps": "Buka petunjuk arah ke Pandiga Cimahi di Google Maps",
  "Guest postcard installation preview": "Pratinjau kumpulan kartu pos tamu",
  "Write": "Tulis", "Draw": "Gambar", "Your message": "Pesanmu",
  "Drawn, not written.": "Digambar, tanpa tulisan.",
  "Postcards from our guests": "Kartu pos dari tamu kami", "See every postcard": "Lihat semua kartu pos", "Click the paper and write — or switch to Draw and sketch over it.": "Klik kertasnya lalu tulis — atau pilih Gambar untuk mencoret di atasnya.",
  "Your postcards": "Kartu posmu", "New card": "Kartu baru", "Update this card": "Perbarui kartu ini", "Edit": "Ubah",
  "In review": "Sedang ditinjau", "Approved": "Disetujui", "Loading your postcards…": "Memuat kartu posmu…",
  "Nothing here yet — your card will appear beside this note once you keep it.": "Belum ada apa pun di sini — kartumu akan tampil di sebelah catatan ini setelah kamu menyimpannya.",
  "You are editing a card you kept before. Saving sends it back for review.": "Kamu sedang menyunting kartu yang sudah disimpan. Simpan ulang akan meninjaunya kembali.",
};
