export const KEEPSAKE_UI_EN = {
  "pageTitle": "Keepsake — Iga dan Bagas",
  "loading": "Preparing your card…",
  "downloadsAria": "Download your card",
  "progressAria": "Preparing video",
  "hintFront": "Tap the card to read your note.",
  "hintBack": "Tap the card to return to the front.",
  "hintNext": "Tap the card to continue your note.",
  "downloadFront": "Save front image",
  "downloadBack": "Save back image",
  "downloadBackPage": "Save back image · {page}/{pages}",
  "downloadVideo": "Save video",
  "downloadVideoReady": "Download MP4 video",
  "cancel": "Cancel",
  "preparingImage": "Preparing image…",
  "imageReady": "Your image is ready to save.",
  "preparingVideo": "Preparing video… {progress}%",
  "videoReady": "Your video is ready. Tap to download.",
  "videoCancelled": "Video preparation cancelled.",
  "imageFailed": "The image could not be saved. Please try again.",
  "videoFailed": "Video could not be made in this browser. You can still save the images.",
  "loadFailed": "Your card could not load. Please open it again.",
  "graphicsFailed": "The image can still be viewed and saved.",
  "frontAria": "Card for {name}. {hint}",
  "backAria": "Note for {name}. {message} {hint}"
} as const;
export const KEEPSAKE_UI_ID = {
  "pageTitle": "Keepsake — Iga dan Bagas",
  "loading": "Menyiapkan kartumu…",
  "downloadsAria": "Unduh kartu",
  "progressAria": "Menyiapkan video",
  "hintFront": "Ketuk kartu untuk membaca pesan.",
  "hintBack": "Ketuk kartu untuk kembali ke depan.",
  "hintNext": "Ketuk kartu untuk melanjutkan pesan.",
  "downloadFront": "Unduh gambar depan",
  "downloadBack": "Unduh gambar belakang",
  "downloadBackPage": "Unduh gambar belakang · {page}/{pages}",
  "downloadVideo": "Unduh video",
  "downloadVideoReady": "Unduh video MP4",
  "cancel": "Batalkan",
  "preparingImage": "Menyiapkan gambar…",
  "imageReady": "Gambar siap disimpan.",
  "preparingVideo": "Menyiapkan video… {progress}%",
  "videoReady": "Videonya siap. Ketuk untuk mengunduh.",
  "videoCancelled": "Pembuatan video dibatalkan.",
  "imageFailed": "Gambar belum bisa disimpan. Coba lagi.",
  "videoFailed": "Video belum bisa dibuat di browser ini. Gambar tetap bisa disimpan.",
  "loadFailed": "Kartunya belum bisa dimuat. Coba buka kembali.",
  "graphicsFailed": "Tampilan gambar tetap bisa dibuka dan disimpan.",
  "frontAria": "Kartu untuk {name}. {hint}",
  "backAria": "Pesan untuk {name}. {message} {hint}"
} as const;
export type KeepsakeUiKey = keyof typeof KEEPSAKE_UI_EN;
